name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - master  # Trigger this workflow only on push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to AWS ECR
      env:
        AWS_REGION: 'us-east-2'
      run: |
        aws ecr get-login-password --region $AWS_REGION --profile default | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_REPOSITORY }}

    - name: Build Docker Image
      run: |
        docker build -t rgb-lightning-node:latest .

    - name: Tag Docker Image
      run: |
        docker tag rgb-lightning-node:latest ${{ secrets.AWS_ECR_REPOSITORY }}:${{ github.sha }}

    - name: Push Docker Image to ECR
      run: |
        docker push ${{ secrets.AWS_ECR_REPOSITORY }}:${{ github.sha }}

    - name: Verify pushed image
      run: |
        echo "Image ${{ secrets.AWS_ECR_REPOSITORY }}:${{ github.sha }} has been successfully pushed."
